### ISSUE TITLE
Populate should error when related entity is not found

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-hooks-common#135]
### Steps to reproduce

The issue is [this block](https://github.com/feathersjs/feathers-hooks-common/blob/master/src/services/populate.js#L188-L194). If results are empty it should probably throw an error or return an empty object. Instead it returns `[]` which is not expected.

I encountered this by having hooks run on the child service that limited the results but this could easily happen if the related child entity was removed without updating relationships.

### Expected behavior
I think it should toss an error.

### Actual behavior
It returns an empty array and populates that onto the parent.

### System configuration

feathers-hooks-common@3.0.0-pre.1

**Comment by corymsmith** [comment]
Agreed that it shouldn't return `[]`, the risk with throwing an error is that if you're doing a find and 1 records populate fails then the whole query will fail. But if you didn't do that then you have to check for null or `{}` on the client which isn't a good solution either

**Comment by ekryski** [comment]
@corymsmith agreed. The other issue I see with this is when you have a field that may or may not have a value. For example, let's say you have a blog post's comments and you wanted to populate the commenter. If the commenter is intentionally `null` or `undefined` throwing an error wouldn't be appropriate.

I think the best recourse is to retain the original value and possibly put a warning in the logs in development mode? What do you think @feathersjs/core-team?

**Comment by eddyystop** [comment]
Perhaps the philosophy should be to reduce the amount of code needed to handle special circumstances.

In the original example, if you normally get a new prop containing an array of joined records, you should get an empty array. Otherwise you have to have extra code.

If you normally replace an existing prop with an array of joined records, you **really** should get an empty array. Not only do you have the problem in the previous paragraph, but you have a worse additional one. What if the original value of the prop was an array of foreign keys, none of which exist? Now instead of an array of joined items, you would retain an array of foreign keys. Ugly.

So I would suggest the approach resulting in the least special handling is to always create an array (if isArray is true) whether the prop containing the foreign key exists, and whether the foreign key actually exists.

**Comment by ekryski** [comment]
I agree that when `isArray === true` it should return an empty array. When populating and `isArray === false` it should probably return either `null`, `undefined` or `{}`. Personally I prefer either `null` or `undefined` so that it's easier to check the existence of the populated item and if you were expecting the item to be there it will be immediately apparent.

**Comment by eddyystop** [comment]
I'll go with `null` as `undefined` should really mean the prop isn't
defined, and as `{}` is too akward to deal with.

**Comment by eddyystop** [comment]
Resolved in https://github.com/feathersjs/feathers-hooks-common/pull/171 which will be published as v3.2.1.

If `parentItem[parentField] !== undefined` and no records are found for the join, `parentItem[nameAs]` will be `asArray ? [] : null`.
