### ISSUE TITLE
Support $search in query syntax

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#141]
This might be a bit tricky because we might need the user to specify the DB or to inspect the service type in order to determine the format but a hook can totally be registered at the app level to enable search capability for a service.

Here is a quick first stab:

```js
// Called like this
// const query = {
//  $search: { name: 'foo' }
// }

function(hook) {
    if (hook.params.query && hook.params.query.$search) {
      const $search = hook.params.query.$search;

      const keys = Object.keys($search);

      if (keys.length) {
        const key = keys[0];
        const searchTerm = $search[key];
        hook.params.query[key] = {
          $regex: `(${searchTerm})`,
          $options: 'si'
        };
      }

      delete hook.params.query.$search;
    }
  };
```

**Caveats for above example:**

- This only works for one property currently. It should be expanded to support multiple
- This is for mongodb/mongoose. It should be expanded for more DBs.

Reference to https://github.com/feathersjs/feathers/issues/334

**Comment by ekryski** [comment]
I'm still on the fence on this because the syntax depends on the database and we might need to inspected deeply nested keys in the `hook.params.query` object. We might be able to make one where you pass the database type as an option and we map the correct query based on that.

This is really common functionality so I think we should seriously considering doing it but it might take a while to get it right. We can iterate though...

@eddyystop since you are the wizard with nested objects would you be up for tackling this?

**Comment by eddyystop** [comment]
I would like firm information based on real-life experience concerning the syntax for the DBs we choose to select.

**Comment by arve0** [comment]
My two cents.

> because the syntax depends on the database

Agree on this. To me it makes sense that code for `$search` should live in the database connectors. Maybe it should be implemented as a hook, but should not live in feathers-hooks-common.

> might need to inspect deeply nested keys in the hook.params.query object

Should the client be able to choose which fields to search in? Sounds like a DOS vulnerability. `query: { fieldName: { $search: 'qwerty' } }` makes sense (and would be nice), but maybe `{ query: { $search: 'qwerty' } }` enough and is what most people need.

#### My idea
1. Top level `$search` will search all properties:
  ```js
  db.find({ query: {
    $search: 'text to search for'
  }})
  ```
2. Server should limit which fields one can search in:
  ```js
  app.hooks({
    before: {
      // allow searching all properties
      find: [ search() ]
      // search only in small text fields, to avoid DOS attacks
      find: [ search({ fields: 'title', 'description' }) ]
    }
  })
  ```
3. Database implementation makes sure string is padded with `*`, `%` or whatever the database uses for text searching. Different databases connectors should sanitize the string before searching.
4. `$search` is implemented by a hook, so that it is disabled by default to avoid DOS attacks.

I've implemented this in the plugin [feathers-nedb-fuzzy-search](https://github.com/arve0/feathers-nedb-fuzzy-search).

**Comment by eddyystop** [comment]
@arve0 Nice work on that. My concern is implementing something similar for all the adapters Feathers supports.

We would want the hook to be DB agnostic, which means it needs to know what adapter the service is using. That info is not available to the hook ATM.

**Comment by daffl** [comment]
Should we close this? I think our [FAQ on searching](https://docs.feathersjs.com/faq/readme.html#how-do-i-do-search) is pretty extensive. I'm not sure if the work for a common hook (that isn't really common since it depends on the adapter) would be worth it?

**Comment by arve0** [comment]
@eddyystop By assuming you want it to be a text search for "every" field (the server side should define which fields to search), one may shim the differences in the hook. See for example the differences in implementation between [nedb hook](https://github.com/arve0/feathers-nedb-fuzzy-search) and [mongodb hook](https://github.com/arve0/feathers-mongodb-fuzzy-search). The server side hook will in other words need to 

1. Escape search string for given database.
2. Pad `*`, `%` or similar around search string for full text search.
3. Use correct method for current database connector.

For example `%${escapedSearchString}%` for SQL-like databases.

This will allow search syntax to be equal for all databases, by using the "simpler" approach (search all fields, text only). The obvious minus is the loss of special search syntax, like `match*something` (star being every char). If one need something more complex, one should probably write a [custom route](https://docs.feathersjs.com/faq/readme.html#how-do-i-do-nested-or-custom-routes).

**Comment by eddyystop** [comment]
I think we're all agreeing to close this.
