### ISSUE TITLE
what's the realtionship between this and feathers-hooks?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-hooks-common#3]
I found many of hooks in this package has been added to feathers-hooks out-of-box?

**Comment by daffl** [comment]
In the next version (1.6.0) of `feathers-hooks` this package will be exported instead of the [bundled](https://github.com/feathersjs/feathers-hooks/blob/master/src/bundled.js) hooks.

In Feathers 3.0 `feathers-hooks` [will become part of core](https://github.com/feathersjs/feathers/issues/408) and you will have to import this package separately.
