### ISSUE TITLE
Normalize hook.result from mongoose and sequelize

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#39]
Should we have every hook that uses hook.result first normalize it?

```javascript
      // If it's a mongoose model then
      if (typeof obj.toObject === 'function') {
        obj = obj.toObject(); 
      }
      // If it's a Sequelize model   
      else if (typeof obj.toJSON === 'function') {
        obj = obj.toJSON();
      }
```

I believe there is an app wide call to do this after the CRUD operation. But it seems we keep getting questions on Slack from people who are new to Feathers.

**Comment by j2L4e** [comment]
Using the `pluck` hook on a Sequelize result throws `Cannot read property 'include' of undefined`.
It took me quite some time to figure out what the actual problem was. So I think hooks should either normalize by default or handle the error at least in development mode and provide a proper error message.
I

**Comment by eddyystop** [comment]
The next version of adapters for MongoDB and Sequelize will configure them for raw return data by default. That can be overriden by a flag.
